### PR TITLE
Add Danish translation

### PR DESCRIPTION
**Pull request by lianergoist**
Adding danish strings

### CODE REVIEW

**Comment by falzonv** [comment]
Hello @lianergoist,

Thank you very much for translating Discreet Launcher!

Just so that you are not surprised, I should mention that the next release will probably not come before one or two months as I am currently very busy with my job.

---

Could you also translate the 3 files for F-Droid metadata? ("title.txt", "short_description.txt", "full_description.txt")
Below, the reference files are in folder "en-US" and the new folder should be named "da":
https://github.com/falzonv/discreet-launcher/tree/main/fastlane/metadata/android

(If you could do it in this same Pull Request, that would make it easier for me to integrate later.)

---

Could you also translate the two following lines that will be added at the end of the Google Play description?
You can write the translation as a comment in this Pull Request and I will copy-paste it.

```
Discreet Launcher is also available on F-Droid.
Source code: https://github.com/falzonv/discreet-launcher
```

---

Could you do the same for the screenshot texts below?
Then I will create the image by copy-pasting the translations at the right places.

Banner:
```
  Discreet Launcher

for a distraction-free
     home screen
```

Screenshot 1:
```
      Enjoy a clean home screen,
while accessing everything in an instant!
```

Screenshot 2:
```
Quick access to your favorite applications...
               (swipe down)
```

Screenshot 3:
```
...or to any other application!
         (swipe up)
```

Screenshot 4:
```
Access favorites from anywhere,
   thanks to the notification!
```

---

Best regards.

**Comment by lianergoist** [comment]
I have translated the three other files. I am sorry I didn't managed to make it into one pull request.


 Google Play description:

Discreet Launcher er også tilgængelig fra F-Droid.
Kildekode: https://github.com/falzonv/discreet-launcher


 screenshot:
 
Banner:

  Discreet Launcher

for en distraktionsfri
startskærm

Screenshot 1:

Nyd en ren startskærm,
mens du får adgang til alt på et øjeblik!

Screenshot 2:

Hurtig adgang til dine yndlingsapplikationer...
                (stryg ned)

Screenshot 3:

...eller til enhver anden applikation!
          (stryg op)

Screenshot 4:

Få adgang til favoritter hvor som helst,
   via notifikationsbjælken!

**Comment by falzonv** [comment]
Hello,

Thank you very much for the additional translations!
I will regroup all of this and create the screenshots when I have some time (maybe this week-end, not sure).

Best regards.

**Comment by falzonv** [comment]
Hello,

This is now merged and, if everything goes well, I should be able to publish the next version somewhere in December.
A few new strings will probably have to be translated in the meantime, I will post about this in the ticket #80.

Best regards.

**Pull request merged**
