### PR TITLE
Enhanced icon pack support

### LINKED ISSUE #336: Icon pack: Folder icon always turns white
All folder icons are monochromatic white when the icon pack corresponding to Discreet Launcher is applied (Arcticons are white line icons so I can't find this problem).
I think it is related to the color filter setting for each folder icon.

| Arcticons | Arcticon White(black-line) | Arcticons Material You | Delta |
| :-: | :-: | :-: | :-: |
|discreet-launcher_with_arcticons|discreet-launcher_with_arction-black|discreet-launcher_with_arcticons-material-you|discreet-launcher_with_delta|

### PR DESCRIPTION
**Pull request by kaanelloed**
Here's my proposal to fix #336 .

First of all, I created the BlankFolderIcon class to prevent the icon from changing size, and created the searchInMultipleIconPack() function to clean up the code.

The logic is therefore that we have a default icon pack icon that refers to “discreetlauncher.folder/discreetlauncher.folder” which will be used if no icon is found for the icon pack at “discreetlauncher.folder/discreetlauncher.folder[# applications]”. If both are absent, the icon will be drawn as before.

I've also added a cache to prevent icon packs from being searched several times for the same number of applications.

### CODE REVIEW

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion and sorry for the delay...

Here are some things that come to my mind after a first reading:
- The BlankFolderIcon and FolderIcon classes are very similar, there is probably a way to adapt the existing FolderIcon class to handle both cases and limit code duplication (maybe by providing "-1" as number of apps to the constructor when we should be in the "BlankFolderIcon case"?).
- I would remove the cache to simplify the code, I don't think it is really needed because most users probably don't have more than 3-4 folders and the probability of them containing exactly the same number of apps is quite low.
- In case there is no folder size icon in the pack but there is a default icon pack icon, the text for the number of icons should be displayed on top of it (maybe with the user-defined color) so that users do not lose this information (especially because I am not sure icon pack maintainers would really create dozens of icons just for my app - there is no limit to the number of apps in a folder -, so the default icon pack icon may be the most used one).

Could you have a look at these points?

Best regards.

**Comment by kaanelloed** [comment]
I'll look into these points

**Comment by kaanelloed** [comment]
@falzonv All the points are done

If the folder size icon exists, it is drawn as is. If a default folder icon exists, it is drawn with centered text and user-defined color, but the icon itself is not colored. If no icon exists, the Discreet folder icon is drawn as before.

**Comment by falzonv** [comment]
Great, thank you!
I will have a look and probably merge it soon

**Comment by kaanelloed** [comment]
I just made a PR in Arcticons to include folder with number :)

**Comment by falzonv** [comment]
Ok cool, thank you for the info!

**Comment by kaanelloed** [comment]
@falzonv And I was thinking of adding icon pack support for the search app, since everything else has it.

It's not quite within the scope of this PR, but it's a very small change, should I add it to this PR or make a new one ?

**Comment by falzonv** [comment]
Hello,

Sorry I missed your last message, good idea for adding icon pack support for the search as well.
You can add it in this PR, as it's still related to icon pack support, but maybe adjust the PR title to be more generic.

Best regards

**Comment by kaanelloed** [comment]
It's done, I wasn't sure what to give it as a new title, I hope it's not too generic.

**Comment by falzonv** [comment]
Perfect, thank you!

**Pull request merged**
