### PR TITLE
Fresh phone screenshots

### PR DESCRIPTION
**Pull request by Donnnno**
### Description

Hi! I've made some new screenshots because they could use a refresh :^) 
Also added a background to make it more complete.

Let me know what you think! 

(I used Arcticons in the screenshots because it fits really well with the discreet launcher)

### CODE REVIEW

**Comment by tuch96** [comment]
@falzonv I like the screenshots very much. Also the different representations of the setting options!  I have also installed the icon packs myself. They harmonise well with the launcher.

**Comment by Donnnno** [comment]
@tuch96 Thanks!

**Comment by falzonv** [comment]
Hello @Donnnno,

Thank you for the suggestion, indeed these screenshots look nice!
However, and I hope you won't take it bad, they have an issue that makes me prefer the current screenshots.

When looking at screenshots in an app store, I expect that when I install the app I retrieve more or less what was pictured in the screenshots (knowing there will be minor variations across versions and devices).
This is why the current screenshots picture how Discreet Launcher looks like "by default". It is what people will get when they click "Install" and it is very important for me that this reflects the reality (admittedly I would be a very bad salesman :joy:).

As a user seeing the screenshots you propose, I would expect that Discreet Launcher looks like this when I install it (as if it was directly embedding Arcticons in the package). Of course this will not be the case: even if Arcticons was already installed on the phone, the default setting is to use default icons so the user would have to select it manually.
To me this would be like false advertising (not sure the word "advertising" is appropriate for a free app, but you get the idea), most probably many users would be disappointed by Discreet Launcher which "does not look like the screenshots".

Please note that this is not specifically related to Arcticons, I would have exactly the same remarks with any icon pack.
Yours fits indeed really well with Discreet Launcher and I also really like this icon pack (this was the first one I tested when adding icon packs support in v1.1.0), but using my app screenshots to promote it at my detriment seems a bit much...

Best regards.

**Comment by Donnnno** [comment]
Hi! Thanks for the reply no worries, I understand you :^) 

>  I would expect that Discreet Launcher looks like this when I install it 

Fair point! I was doubting about this when I was creating it too, it's also possible without an icon pack in the screenshots if you want to!

**Comment by Donnnno** [comment]
Something like this is still an option if you like it:

**Comment by falzonv** [comment]
Hello,

Ok thank you for your understanding and the new suggestion!

Let's reopen the pull request then, and I will think about it in January (currently I am away, just dropped by to see answers to the latest topics).

Best regards.

**Comment by Donnnno** [comment]
Take your time! And enjoy the vacation

**Comment by falzonv** [comment]
Hello @Donnnno and happy new year!

Thank you again for the new proposal, looking at it today and I think we should give it a try :-)

I also like that it shows some LineageOS and F-Droid apps, this is not the case with the current screenshots because they were created using an Android Studio emulator.
By the way, feel free to include Arcticons or any other good F-Droid app in the list of apps ;-)

Before merging it, I still have a couple of remarks listed below:

- The phone pictures of 2nd and 3rd screenshots do not match the texts and should be inverted. Not sure however how to make this fit with the alternating cut-up/down phones...
Maybe with a "complete" phone on the 1st screenshot (like the 5th screenshot but with the text above), then a cut-down phone for the 2nd screenshot (favorites), a cut-up for the 3rd (light app drawer with names), a cut-down for the 4th (dark app drawer without names), and keep a complete phone like now on the 5th screenshot?
- I do not think the 5th screenshot is really useful, the favorites selector is not so interesting and the current selection doesn't match the screenshot where we see the favorites panel.
Maybe an idea to replace this 5th screenshot: below on the right is the current 4th screenshot where we see the favorites called over another app using the quick-access notification.
*Note: the selected favorites are matching those of the current 2nd screenshot (below on the left) for consistency ; also, I choose the calculator as background because it is kind of a neutral app that everyone has.*

- I am not sure about the clock on the 1st screenshot. It looks good and is an occasion to show this clock that took me hours to work on, but the original point of the launcher was to have an empty home screen showing only the wallpaper.

Could you have a look on these points?

Best regards.

**Comment by Donnnno** [comment]
Thanks for the feedback! I'll take a look at it when I have some time :^)

**Comment by Donnnno** [comment]
Working on this, the only thing I haven't figured out is how to get the favorite screen above of another app!

**Comment by falzonv** [comment]
Hello,

Great, thank you for the follow-up!

For the favorites above another app, you need to enable "Notification for access to favorites" in the menu "Operation", this will add a notification called "Favorites" in the notifications panel (it uses a transparent icon to not be too intrusive).
Then when you are in another app, open the notifications panel and click the "Favorites" notification. It will display the favorites panel on a dimmed background like on the current 4th screenshot.

Best regards.

**Comment by Donnnno** [comment]
Ah, thanks! This is what I have right now:

**Comment by falzonv** [comment]
Wow, this looks really awesome! Nice work!
I like also the "v" and "^" signs, very good idea, and the wallpaper is more beautiful than the previous one in my (admittedly subjective) opinion :-)

For the first screenshot, could you try with a complete phone?
Looking at the 4th screenshot it seems the text would not fit, but maybe the phone and text margins from 1st screenshot could be made a bit smaller than 2nd and 3rd screenshots to allow it?

Maybe for symmetry the phone for 4th screenshot should then be reduced to match the phone from 1st screenshot (although currently the phone from 4th screenshot has a different size, as we can see at https://vincent-falzon.com/en/images/discreet-launcher/index.html).
Another (maybe complementary) option for real symmetry would be to have a text above the complete phone of the 4th screenshot. Something like "Access favorites from anywhere thanks to a notification!" could work but any ideas are welcome :-)

**Comment by falzonv** [comment]
Hello @Donnnno,

For information I plan to publish the next release v6.0.0 on 17th February 2022, exactly one year after [v1.0.0](https://github.com/falzonv/discreet-launcher/releases/tag/v1.0.0).
It would be a good opportunity to use the new the screenshots with this new release :-)

No pressure however, this was just an idea coming through my mind and there is really no issue to update the screenshots later if you are too busy at the moment.

Best regards.

**Comment by Donnnno** [comment]
Hi! Sorry, I was kinda busy for the last weeks! But I can finish this before the deadline, no problem!

**Comment by Donnnno** [comment]
Also, if you need any other help with design stuff, let me know! I'm happy to help :^)

**Comment by falzonv** [comment]
Hello @Donnnno,

Great, thank you for the update!

> Also, if you need any other help with design stuff, let me know!

Thank you for the proposal!
Maybe the "feature graphic" could be replaced if you have some ideas, this was something I created in a hurry when discovering it was mandatory for Google Play but I never really thought again about it.
I see in the PR that you made some adjustments to it, looks already better :-)

After, I am currently happy with the Discreet Launcher app icon (made myself) and the main menu icons (they come from Android stock, look nice and work well with both light and dark themes).

Best regards.

**Comment by falzonv** [comment]
Hello,

Just a kind reminder that the next release will be published next week ;-)

Best regards.

**Comment by Donnnno** [comment]
Yes! Just got back from Paris and this was on my todo-list for this weekend! 

Here are the new phone screenshots with your feedback, and a feature graphic! I can also update the background of the icon to match the other graphics more!


featureGraphic

If these are good to you, I'll create a PR and add them :^)

**Comment by falzonv** [comment]
Hello,

Awesome, thank you for the update!

I have only two remarks:
- Could you vertically center the 1st and 4th screenshots so that the top and bottom margins look more similar? (in case the screenshots are viewed one by one)
- On the 4th screenshot, the left border of the favorites popup looks missing, it is cut off by a few pixels. This made me double check on my phone in case it was a bug in the launcher :joy:, now I can confirm that all four sides of the popup border are the same width. Could you fix it?

Otherwise everything looks good for me, great work! :-)

> I can also update the background of the icon to match the other graphics more!

=> Maybe someday, for now I prefer to keep the icon as-is.

*Note: when everything is ready, you can update directly this PR by pushing new commits to it, no need to create a new PR* ;-)

Best regards.

**Comment by Donnnno** [comment]
Like this?

**Comment by falzonv** [comment]
Perfect, this indeed looks more centered when screenshots are viewed individually :-)
Once the left border of the favorites popup is fixed, I think we are good!

*Note: out of home currently so I will merge the PR only tomorrow evening, I want to check before that I have no local commits pending on my computer.*

**Comment by comradekingu** [comment]
Nyt en ren hjemmeskjerm,
selv om du har tilgang til alt.

Hurtigtilgang til favorittprogrammer …
(dra nedover)

… eller alle andre programmer.
(dra oppover)

Tilgang til favoritter fra hvor som helst,
takket være merknaden.


Diskret oppstarter
en distraksjonsfri hjemmeskjerm
---

I am thinking it should be "homescreen" maybe?
It also says "you favorite applications", where I would go "your favourite"
Since it is "applications" in the next one, could drop applications from that.
There is 3x "access", that could be intended.
Clear is much better than "clean". I like it.
The last one isn't as self-explanatory. I don't really use notifications, so I don't know.
down is "downwards" in my head, but I think the angle-arrows are enough.

Enjoy a clear homescreen,
with everything within reach.

Open favourites quickly
(swipe  ↓)

…or any other application.
(swipe ↑)

Access favourites from anywhere,
thanks to the notification.

---

A clear homescreen, with shortcuts
← and →

Open favourites
     ↓

…or any other application.
     ↑

Favourites from anywhere,
with the notification.

Discreet Launcher
a distraction-free homescreen

**Comment by Donnnno** [comment]
@falzonv uploaded the new screenshots!

**Comment by comradekingu** [comment]
@Donnnno What do you think about the simpler texts?

**Comment by Donnnno** [comment]
I'm ok with it! If @falzonv likes it too, I'll change it :^)

**Comment by falzonv** [comment]
Hello,

Thank you @Donnnno for the new screenshots, it's perfect and they look awesome!

*Out of curiosity, is "screenshots_total.jpg" used for something in F-Droid?
I will probably use it when updating the GitHub home page but this is to know if I also need to copy it in other translations.*

---

Thank you @comradekingu for the translation and your feedback!

I agree that "clear" is better than "clean" (1st screenshot) and "the notification" is better than "a notification" (4th screenshot).

For the other things, I prefer the current version.
Very often the screenshots will be seen individually in the F-Droid client so repetition of some words among them is not really an issue (actually it might even be better for continuity).
Regarding the notification, in the current 4th screenshot there is no text at all so we are improving anyway :-) If this makes people fiddle a bit in the settings that's good as they might discover other things useful for them in the process (although everything is already listed in the description, but many people skip descriptions...).

About the swipes, I prefer the current "(swipe up)" / "(swipe down)" to the proposed "(swipe upwards)" / "(swipe downwards)", for me both mean the same thing and the firsts one are simpler.
I prefer to keep both the "(swipe up/down)" texts and arrows, but your remark make me think that on 3rd screenshot it may look better to have the "(swipe up)" text moved above "...or to any other application!" (more symmetric with 2nd screenshot).

---

@Donnnno:
As per my feedback above, could you please apply these 3 text modifications?
- Screenshot 1: replace "clear" by "clean"
- Screenshot 3: exchanges the lines "(swipe up)" and "...or to any other application!" so that "(swipe up)" is next to the arrow (this will be diagonally symmetric with screenshot 2)
- Screenshot 4: replace "a notification" by "the notification"

Best regards.

**Comment by Donnnno** [comment]
You can use screenshots_total right here on Github, if you want to. They aren't for F-Droid! 

I'll change it right away!

**Comment by Donnnno** [comment]
Like this? 

image

**Comment by falzonv** [comment]
Yes for the swipe up, this was exactly what I meant!

---

After double-checking in a dictionary it appears that "clean" was in fact more accurate than "clear"... could we keep "clean"?
Really sorry for the back-and-forth... :-/

**clean**
*Something that is clean is free from dirt or unwanted marks.*
https://www.collinsdictionary.com/dictionary/english/clean

**clear**
*Something that is clear is easy to understand, see, or hear.*
https://www.collinsdictionary.com/dictionary/english/clear

**Comment by Donnnno** [comment]
Clean sounds more logical indeed!

**Comment by falzonv** [comment]
Thank you very much for the last changes, this looks perfect to me!
Again, really nice work!

Let's merge :-)

**Comment by Donnnno** [comment]
Cool! Thanks :^)

**Comment by Donnnno** [comment]
Hi @falzonv, thank you for your donation! 
I just like to help where I can with open-source projects ;)

**Pull request merged**
