### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by odanoburu**
I don't really set my phone's language to Portuguese but I figure someone might find it useful anyway! Here's the requested snippets translated: 

Banner:
  Discreet Launcher
por uma tela inicial sem distrações

Screenshot 1:
      Desfrute de uma tela inicial limpa,
mas com acesso à tudo em um instante!

Screenshot 2:
Acesso rápido aos seus apps favoritos...
               (deslize para baixo)

Screenshot 3:
...ou à qualquer outro aplicativo!
         (deslize para cima)

Screenshot 4:
Acesse seus favoritos de qualquer lugar,
  graças à notificação!

Google Play description:
Discreet Launcher também está disponível no F-Droid.
Código-fonte: https://github.com/falzonv/discreet-launcher

### CODE REVIEW

**Comment by falzonv** [comment]
Hello,

Thank you very much for translating Discreet Launcher!

I wonder, are Brazilian Portuguese and Portugal Portuguese so different that Portugal users would prefer the default English?

If they are not so different, maybe we could make it a common Portuguese translation by using folder names `values-pt` (strings) and `pt` (metadata), like I did with the French translation to include also French Canadian.

Best regards.

**Comment by odanoburu** [comment]
> I wonder, are Brazilian Portuguese and Portugal Portuguese so different that Portugal users would prefer the default English?

I wouldn't really know, but some people don't like our version of the language, and it's a bit more different than French French is from Canadian French, I think. Plus much like the French do, the Portuguese will often create their own name for stuff instead of adapting the English word (think `ordinateur`), so it would be difficult to reconcile some words for basic things like files (`arquivos` versus `ficheiros`).

But I guess we could have a single version and then if someone complains they are welcome to create another? Should I go ahead and do that?

**Comment by falzonv** [comment]
Hello @odanoburu,

I am really sorry for my late answer, I am very busy with my job this month and didn't even had the occasion to check GitHub since my previous message last week :-/

Thank you for the explanation, I think having a single version would be the best if this is possible as it would cover more users while keeping the updates process simpler.

I am quite sure there are also differences in some words between French from Canada and from France to be honest.
So far no French Canadian ever complained of my French translation (although to be fair I have no idea if I have French Canadian users), but if some did I would either suggest to create another translation, or try to find with them an happy compromise for the part(s) which bother them.

Best regards.

**Comment by odanoburu** [comment]
Hi @falzonv, sorry for the delay (due to wrapping up the year), but it's done now!

**Comment by falzonv** [comment]
Perfect, thank you!
Let's merge it :-)

**Pull request merged**
