### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by ArturAiwasan**
Добавлен русский язык

### CODE REVIEW

**Comment by falzonv** [comment]
Hello Artur,

Thank you for your interest in this project and having taken the time to propose a translation!

Before to integrate this translation, there are a couple of points to discuss:

**1/ Will you update this translation in the future?**
Almost every release introduces new texts (or modify existing texts) and I cannot update this Russian translation myself (I speak only French and English ; for example I have no idea of what you wrote in your comment above).

**2/ Sorry to insist, but will it be the case also in 6 months? And in 1 or 2 years?**
If not, do you have an idea to make sure that the Russian translation will stay up-to-date even on long term?

**3/ What will be the process to update this translation?**
This is the first time a translation would be added to the application so currently there is no process.
Do you already have some ideas about a good way to do this?

**4/ GitHub tickets can be opened only in English or French because I do not speak other languages. I would like to make it clear for users to avoid disappointments and confusions.**
Maybe we could add something like the following text (in Russian) at the end of the "About" section:

> "This Russian translation is offered to you by Artur Aiwasan.
If you need to contact Vincent, please do it in English or French."

This would be displayed only when the Russian translation is used. Do you think it can work?
If yes, could you provide me the Russian translation of the text above?
If no, do you have another idea to solve this point?

Thank you in advance for your answers.

Best regards.

**Comment by ArturAiwasan** [comment]
> **1/ Will you update this translation in the future?**
> Almost every release introduces new texts (or modify existing texts) and I cannot update this Russian translation myself (I speak only French and English ; for example I have no idea of what you wrote in your comment above).
Jes.

> **2/ Sorry to insist, but will it be the case also in 6 months? And in 1 or 2 years?**
> If not, do you have an idea to make sure that the Russian translation will stay up-to-date even on long term?
Jes.

> **3/ What will be the process to update this translation?**
> This is the first time a translation would be added to the application so currently there is no process.
> Do you already have some ideas about a good way to do this?
I use this software regularly.
Accordingly, translation will also be checked. 

> **4/ GitHub tickets can be opened only in English or French because I do not speak other languages. I would like to make it clear for users to avoid disappointments and confusions.**
> Maybe we could add something like the following text (in Russian) at the end of the "About" section:
> 
> > "This Russian translation is offered to you by Artur Aiwasan.
> > If you need to contact Vincent, please do it in English or French."
> 
> This would be displayed only when the Russian translation is used. Do you think it can work?
> If yes, could you provide me the Russian translation of the text above?
> If no, do you have another idea to solve this point?
Ok. Sen problemoj/no problems.
>Перевод на русский язык предоставил Artur Aiwasan
>Если вам нужно связаться с Винцетом (разработчик), сделайте это на английском или французском языках.

I add this in RU-translation.

**Comment by falzonv** [comment]
Perfect!
Then I will accept the pull request and Russian translation will be added in next release v4.3.0 :-)

Thank you again for your work in translating the application.

**Comment by falzonv** [comment]
Hello @ArturAiwasan,

Please note the creation of ticket #80 that should make it much easier for translations updates (no need to check yourself).
Thank you again for your work in translating Discreet Launcher, highly appreciated!

Best regards.

**Pull request merged**
